export default {
  CSS_TRANSFORM_PREFIX: ['-webkit-', '-moz-', '-ms-', '-o-', ''],
  DIRECTION: {
    DEFAULT: 'DEFAULT',
    PREV: 'PREV',
    NEXT: 'NEXT',
  },
  PERCENT: {
    DEFAULT: '0',
    DOWN: '-100%',
    UP: '100%',
  },
  TAG_ATTRIBUTE: {
    CLASS: 'class',
  },
  CAROUSEL_DOM_INFORMATION: {
    CAROUSEL_TAGNAME: 'div',
    CAROUSEL_CLASSNAME: '_carousel',
    CAROUSEL_DATA_TAGNAME: 'div',
    CAROUSEL_DATA_CLASSNAME: '_carousel_data',
    CAROUSEL_CSS: {
      '-webkit-backface-visibility': 'hidden',
      'backface-visibility': 'hidden',
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      width: '100%',
      height: '100%',
      margin: 0,
      padding: 0,
      border: 0,
    },
    CAROUSEL_DATA_CSS: {
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      // '-webkit-transition': '-webkit-transform 0.2s ease-out',
      // transition: 'transform 0.2s ease-out',
    },
  },
};
